# Generated by Django 5.0.3 on 2024-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='isLike',
            field=models.BooleanField(default=False),
        ),
    ]
