# Generated by Django 5.0.3 on 2024-04-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_bio_alter_customuser_located_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
