# Generated by Django 5.0.3 on 2024-04-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customuser_friends_count_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribers_count',
            field=models.IntegerField(default=0),
        ),
    ]
