# Generated by Django 5.0.3 on 2024-04-11 13:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_customuser_subscribers_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default_avatar.jpg', max_length=255, verbose_name='image'),
        ),
    ]
