# Generated by Django 5.0.3 on 2024-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuser_bio_alter_customuser_located'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='01.01.2000', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='located',
            field=models.CharField(blank=True, default='Ivano-Frankivsk', max_length=25),
        ),
    ]
