# Generated by Django 5.0.4 on 2024-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_customuser_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reel_count',
            field=models.IntegerField(default=0),
        ),
    ]
