# Generated by Django 5.0.4 on 2024-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_customuser_reel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stories_count',
            field=models.IntegerField(default=0),
        ),
    ]
