# Generated by Django 5.0.4 on 2024-05-03 19:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_story_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='video',
        ),
        migrations.AddField(
            model_name='story',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='media'),
        ),
    ]
