# Generated by Django 5.0.4 on 2024-05-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_remove_story_image_remove_story_video_story_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_data',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='commentstory',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.story'),
        ),
    ]
