# Generated by Django 5.0.4 on 2024-05-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_rename_story_data_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
